name = "bible-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "WORDS_KV"
id = "fbedb6d296734a35959992c3efe92363"
preview_id = "REPLACE_WITH_DEV_KV_ID"
